#!/bin/sh
processes="zte_mqtt_sdk ztedm_timer ztedm"
for process in ${processes}; do
   pid=$(ps | grep -v grep | grep ${process} | awk -F' ' '{print $1}')
   if [ -n "${pid}" ]; then
       kill ${pid}
   fi
done
sleep 20
counter=0
while true; do
    pid=$(ps | grep -v grep | grep zte_webadmin | awk -F' ' '{print $1}')
    if [ -z "${pid}" ] ; then
        zte_webadmin &
    else
        counter=$(expr ${counter} + 1)
        if [ ${counter} -ge 360 ]; then
            kill ${pid}
            zte_webadmin &
            counter=0
        fi
    fi
    sleep 10
done
